apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: signoz-ui
  namespace: monitoring
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`signoz.private.ksa-1.datixcloudiq.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: signoz-restricted
          port: 8080
