apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: signoz
  namespace: monitoring
spec:
  entryPoints:
    - web
    # - websecure  # uncomment if you also want HTTPS
  routes:
  - kind: Rule
    match: Host(`monitoring.private.ksa-1.datixcloudiq.com`) && PathPrefix(`/`)
    middlewares:
    - name: signoz-whitelist
      namespace: monitoring
    services:
    - kind: Service
      name: signoz-restricted
      namespace: monitoring
      port: 8080
